services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_ROOT_PASSWORD:-pathary}
      MYSQL_USER: ${DATABASE_MYSQL_USER:-pathary}
      MYSQL_PASSWORD: ${DATABASE_MYSQL_PASSWORD:-pathary}
      MYSQL_DATABASE: ${DATABASE_MYSQL_NAME:-pathary}
      MYSQL_PORT: ${DATABASE_MYSQL_PORT:-3306}
    volumes:
      - pathary-database:/var/lib/mysql
    ports:
      - "${DATABASE_MYSQL_PORT:-3306}:3306"

  app:
    environment:
      DATABASE_MODE: "${DATABASE_MODE:-mysql}"
      DATABASE_MYSQL_HOST: "${DATABASE_MYSQL_HOST:-mysql}"
      DATABASE_MYSQL_NAME: "${DATABASE_MYSQL_NAME:-pathary}"
      DATABASE_MYSQL_USER: "${DATABASE_MYSQL_USER:-pathary}"
      DATABASE_MYSQL_PASSWORD: "${DATABASE_MYSQL_PASSWORD:-pathary}"
      DATABASE_MYSQL_PORT: "${DATABASE_MYSQL_PORT:-3306}"

volumes:
  pathary-database:
